project_id = "evmamwdmwogmlezndueg"

[functions.generate-speech]

[functions.extract-transcript]

[functions.poll-transcript-job]

[functions.analyze-content]

[functions.generate-practice-sentences]

[functions.get-available-languages]

[functions.youtube-search]

[functions.conversation-chat]

[functions.conversation-summary]

[functions.send-welcome-email]

[functions.submit-feedback]

[functions.test-apis]
 
 [functions.migrate-project-titles]
 verify_jwt = false
